/*
 * This source file was generated by the Gradle 'init' task
 */
package kau.sh.oss.testing

import kotlinx.coroutines.delay
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.flow
import kotlin.time.Duration.Companion.seconds

class App {
  val greeting: String
    get() {
      return "Hello World!"
    }

  fun myFlow(): Flow<Int> = flow {
    emit(1)
    delay(3.seconds)
    emit(10)
  }
}

fun main() {
  println(App().greeting)
}
