/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.delay
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.launch
import kotlin.time.Duration.Companion.seconds

class App {

  private val _stateFlow = MutableStateFlow(0)
  val stateFlow: Flow<Int> = _stateFlow


  fun start() {
    CoroutineScope(Dispatchers.Default).launch {
      _stateFlow.emit(1)
      delay(3.seconds)
      _stateFlow.emit(10)
    }
  }
}

fun main() {
  println("Coroutine Testing examples - see tests")
}
