/*
 * This source file was generated by the Gradle 'init' task
 */
package kau.sh.oss.testing

import kotlinx.coroutines.ExperimentalCoroutinesApi
import kotlinx.coroutines.test.advanceTimeBy
import kotlinx.coroutines.test.currentTime
import kotlinx.coroutines.test.runTest
import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.DisplayName
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.extension.RegisterExtension
import kotlin.time.Duration.Companion.seconds

@OptIn(ExperimentalCoroutinesApi::class)
class CoroutineTestRuleTest {

  @RegisterExtension
  val testRule = CoroutineTestRule()

  @Test
  @DisplayName("advancement respected by testScope + rule extension")
  fun setupTimeAdvancement() = runTest {
    assertEquals(0.seconds.inWholeMilliseconds, currentTime)
    advanceTimeBy(2.seconds)
    assertEquals(2.seconds.inWholeMilliseconds, currentTime)
    assertEquals(currentTime, testRule.currentTestTime())
  }
}

