/*
 * This source file was generated by the Gradle 'init' task
 */
package kau.sh.oss.testing

import kotlinx.coroutines.ExperimentalCoroutinesApi
import kotlinx.coroutines.delay
import kotlinx.coroutines.job
import kotlinx.coroutines.launch
import kotlinx.coroutines.test.StandardTestDispatcher
import kotlinx.coroutines.test.UnconfinedTestDispatcher
import kotlinx.coroutines.test.advanceTimeBy
import kotlinx.coroutines.test.runCurrent
import kotlinx.coroutines.test.runTest
import kotlinx.coroutines.yield
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Disabled
import org.junit.jupiter.api.DisplayName
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.extension.RegisterExtension
import kotlin.time.Duration.Companion.milliseconds
import kotlin.time.Duration.Companion.seconds

@OptIn(ExperimentalCoroutinesApi::class)
class StandardVsUnconfinedTestDispatcherTests {

  @DisplayName("test StandardTestDispatcher")
  @Test
  fun test1() = runTest(StandardTestDispatcher()) {
    var result = "A"

    launch {
      delay(1.seconds)
      result = "B"
      delay(1.seconds)
      result = "C"
    }

    advanceTimeBy(1.seconds)
    runCurrent()
    assertThat(result).isEqualTo("B")

    advanceTimeBy(1.seconds)
    runCurrent()
    assertThat(result).isEqualTo("C")
  }

  @DisplayName("test UnconfinedTestDispatcher")
  @Test
  fun test2() = runTest(UnconfinedTestDispatcher()) {
    var result = "A"

    val job = launch {
      delay(1.seconds)
      result = "B"
      delay(1.seconds)
      result = "C"
    }

    // advanceTimeBy(1.seconds)
    advanceTimeBy(1.seconds)

    // the job doesn't launch automatically since the coroutine hasn't "started" yet
    assertThat(result).isEqualTo("A")

    // this forces the job to start + complete
    job.join()

    // notice how the result B is ignored
    assertThat(result).isEqualTo("C")
  }

}

